---
title: "TCP Packet"
---
packet-beta
0-15: "Zdrojový port"
16-31: "Cílový port"
32-63: "Sekvenční číslo"
64-95: "Potvrzovací číslo"
96-99: "Posun dat"
100-105: "Rezervováno"
106: "URG"
107: "ACK"
108: "PSH"
109: "RST"
110: "SYN"
111: "FIN"
112-127: "Okno"
128-143: "Kontrolní součet"
144-159: "Ukazatel na urgentní data"
160-191: "(Volby a výplň)"
192-255: "Data (proměnná délka)"
